global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'quarkus-clients-api'
    static_configs:
      - targets: ['http://localhost:8080']
    metrics_path: 'metrics'
    scheme: http